[dev]
port=8080
targetPort=4321
[build]
  [context.dev]
    [build.environment]
      ASTRO_DATABASE_FILE="./netlify/dev.db"
      # Ignored when a url is configured for an audit
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
